<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EList.Repositories.Interfaces\EList.Repositories.Interfaces.csproj" />
    <ProjectReference Include="..\EList.Validators.Interfaces\EList.Validators.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UserDataValidationService\" />
  </ItemGroup>

</Project>
