<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Migrations\InitialDatabase.sql" />
    <None Remove="Migrations\DevelopMigration.sql" />
    <None Remove="Migrations\SoftDeleteCatalogs.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\InitialDatabase.sql" />
    <EmbeddedResource Include="Migrations\DevelopMigration.sql" />
    <EmbeddedResource Include="Migrations\SoftDeleteCatalogs.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentMigrator" Version="3.3.2" />
  </ItemGroup>

</Project>
