<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="linq2db" Version="6.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="8.0.9" />
    <PackageReference Include="Npgsql.NetTopologySuite" Version="8.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EList.Common\EList.Common\EList.Common.csproj" />
  </ItemGroup>

</Project>
